### ISSUE TITLE
`bot.lua` assumes it runs on Lua 5.1, doesn't do any version checks

### ISSUE THREAD

**Issue by RedstoneParkour** [ShoesForClues/BOT#1]
`bot.lua` assumes it runs on Lua 5.1 and doesn't exit cleanly with an `This program only runs on Lua 5.1` error, instead causing an error due to it trying to call global `unpack` (a nil value in Lua 5.2+)
There also isn't anything in the readme that says that it only runs on Lua 5.1.

**Comment by ShoesForClues** [comment]
Well, I _did_ just create this repository a few hours ago. Eventually I'll have all of the documentations ready under the wiki.
As for version checking, I actually plan on releasing the compiler as a standalone executable rather than running under a Lua host. Which of course means I have to finish the C target backend.
